/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme_bullet_collision_shapes_SimplexCollisionShape */

#ifndef _Included_com_jme_bullet_collision_shapes_SimplexCollisionShape
#define _Included_com_jme_bullet_collision_shapes_SimplexCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme_bullet_collision_shapes_SimplexCollisionShape
 * Method:    createShape
 * Signature: (Lcom/jme/math/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme_bullet_collision_shapes_SimplexCollisionShape_createShape__Lcom_jme_math_Vector3f_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jme_bullet_collision_shapes_SimplexCollisionShape
 * Method:    createShape
 * Signature: (Lcom/jme/math/Vector3f;Lcom/jme/math/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme_bullet_collision_shapes_SimplexCollisionShape_createShape__Lcom_jme_math_Vector3f_2Lcom_jme_math_Vector3f_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_jme_bullet_collision_shapes_SimplexCollisionShape
 * Method:    createShape
 * Signature: (Lcom/jme/math/Vector3f;Lcom/jme/math/Vector3f;Lcom/jme/math/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme_bullet_collision_shapes_SimplexCollisionShape_createShape__Lcom_jme_math_Vector3f_2Lcom_jme_math_Vector3f_2Lcom_jme_math_Vector3f_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_jme_bullet_collision_shapes_SimplexCollisionShape
 * Method:    createShape
 * Signature: (Lcom/jme/math/Vector3f;Lcom/jme/math/Vector3f;Lcom/jme/math/Vector3f;Lcom/jme/math/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme_bullet_collision_shapes_SimplexCollisionShape_createShape__Lcom_jme_math_Vector3f_2Lcom_jme_math_Vector3f_2Lcom_jme_math_Vector3f_2Lcom_jme_math_Vector3f_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
