/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme_bullet_collision_shapes_PlaneCollisionShape */

#ifndef _Included_com_jme_bullet_collision_shapes_PlaneCollisionShape
#define _Included_com_jme_bullet_collision_shapes_PlaneCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme_bullet_collision_shapes_PlaneCollisionShape
 * Method:    createShape
 * Signature: (Lcom/jme/math/Vector3f;F)J
 */
JNIEXPORT jlong JNICALL Java_com_jme_bullet_collision_shapes_PlaneCollisionShape_createShape
  (JNIEnv *, jobject, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
