/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme_bullet_collision_shapes_BoxCollisionShape */

#ifndef _Included_com_jme_bullet_collision_shapes_BoxCollisionShape
#define _Included_com_jme_bullet_collision_shapes_BoxCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme_bullet_collision_shapes_BoxCollisionShape
 * Method:    createShape
 * Signature: (Lcom/jme/math/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme_bullet_collision_shapes_BoxCollisionShape_createShape
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
